version: 2
updates:
  - package-ecosystem: npm
    directory: /portfolio-next/Portfolio-main
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
