export type CaseStudy = {
  slug: string; title: string; eyebrow: string; summary: string; demo?: string; repo: string;
  signal?: string; problem: string; approach: string; architecture: string[]; decisions: { title: string; detail: string }[]; limitations: string[]; stack: string[];
};

export const caseStudies: CaseStudy[] = [
  { slug: "sentinelflow", title: "SentinelFlow", eyebrow: "ML systems / decision intelligence", signal: "Synthetic-data reference implementation", summary: "A transparent fraud-risk workflow demo built to make modelling, policy, and review surfaces inspectable.", repo: "https://github.com/snehOP9/Sentinal-Flow", demo: "https://sentinalflow.vercel.app", problem: "Risk workflows can hide important modelling and policy choices behind a single score.", approach: "The reference system joins event-time features, a trained model, policy routing, and an operator-facing dashboard while keeping its synthetic-demo boundary explicit.", architecture: ["Next.js and TypeScript dashboard", "FastAPI service with strict request schemas", "Redis event-time state", "PostgreSQL production path; SQLite test path", "MLflow-tracked training artifacts"], decisions: [{ title: "Explain the operating context", detail: "The system presents model and policy signals as decision support, not as a substitute for review." }, { title: "Keep evaluation reproducible", detail: "The repository documents synthetic generation, temporal splitting, calibration, and tracked artifacts." }], limitations: ["Synthetic data only; it is not a banking or compliance system.", "Counterfactual signals are non-causal and require human interpretation."], stack: ["FastAPI", "Next.js", "Redis", "PostgreSQL", "MLflow"] },
  { slug: "student-performance-predictor", title: "Student Performance Predictor Pro", eyebrow: "Full-stack ML application", summary: "An authenticated student-performance application connecting prediction, uncertainty, and recommendations through a focused web interface.", repo: "https://github.com/snehOP9/student-performance-api", demo: "https://student-performance-predictor-pro-w.vercel.app/", problem: "A prediction interface needs more than a score: people need an understandable workflow around it.", approach: "A FastAPI backend exposes health, prediction, uncertainty, recommendation, and authenticated-user endpoints for a React and TypeScript client.", architecture: ["FastAPI backend", "Prediction and uncertainty endpoints", "Recommendation endpoint", "Authentication and current-user endpoints", "React, TypeScript, and Vite frontend"], decisions: [{ title: "Expose uncertainty", detail: "The API separates prediction and uncertainty paths rather than implying an unqualified answer." }, { title: "Make workflows authenticated", detail: "Sign-up, login, and user endpoints support a scoped product experience." }], limitations: ["Portfolio documentation describes the interface and API surface, not a validated educational intervention.", "No outcome or accuracy claims are made here."], stack: ["Python", "FastAPI", "React", "TypeScript", "Vite"] },
  { slug: "anony-talk", title: "Anony Talk", eyebrow: "Community web application", summary: "An anonymous community product for lightweight reflection and peer interaction.", repo: "https://github.com/snehOP9/anony-talk", demo: "https://anony-talk-safespace.vercel.app/", problem: "Low-friction social spaces need clear boundaries when they invite personal reflection.", approach: "The application combines anonymous posts, peer interaction, chat-oriented features, and account security in a React and Express stack.", architecture: ["React and Vite client", "Node.js and Express API", "SQLite persistence", "Authentication with bcrypt", "Anonymous posts and peer-interaction features"], decisions: [{ title: "Keep the product boundary explicit", detail: "The portfolio describes this as a community product, not clinical care or crisis support." }, { title: "Use a lightweight web stack", detail: "React, Express, and SQLite keep the project focused on product workflows." }], limitations: ["Not a substitute for professional healthcare or crisis support.", "No safety or clinical efficacy claim is made."], stack: ["React", "Vite", "Node.js", "Express", "SQLite"] },
];

export const getCaseStudy = (slug: string) => caseStudies.find((study) => study.slug === slug);
